--DROP TABLE EMPRESA CASCADE CONSTRAINTS;
--DROP TABLE COMPONENTE CASCADE CONSTRAINTS;
--DROP TABLE TRANSPORTISTA CASCADE CONSTRAINTS;
--DROP TABLE CIUDAD CASCADE CONSTRAINTS;
--DROP TABLE ENVASE CASCADE CONSTRAINTS;
--DROP TABLE RESIDUO CASCADE CONSTRAINTS;
--DROP TABLE COMPOSICION CASCADE CONSTRAINTS;
--DROP TABLE TRASLADO CASCADE CONSTRAINTS;

--DROP SEQUENCE SEQ_EMPRESA;
--DROP SEQUENCE SEQ_COMPONENTE;
--DROP SEQUENCE SEQ_TRANSPORTISTA;
--DROP SEQUENCE SEQ_ENVASE;
--DROP SEQUENCE SEQ_RESIDUO;
--DROP SEQUENCE SEQ_COMPOSICION;
--DROP SEQUENCE SEQ_TRASLADO;

CREATE SEQUENCE SEQ_EMPRESA;
CREATE SEQUENCE SEQ_COMPONENTE;
CREATE SEQUENCE SEQ_TRANSPORTISTA;
CREATE SEQUENCE SEQ_ENVASE;
CREATE SEQUENCE SEQ_RESIDUO;
CREATE SEQUENCE SEQ_COMPOSICION;
CREATE SEQUENCE SEQ_TRASLADO;

CREATE TABLE EMPRESA (ID_EMPRESA NUMBER (9)
                     ,NOMBRE VARCHAR2 (25)
                     ,DIRECCION VARCHAR2 (25)
                     ,NIF VARCHAR2 (25)
                     ,CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA)
                     ,CONSTRAINT UQ_NIF UNIQUE(NIF));
                     
CREATE TABLE COMPONENTE (ID_COMPONENTE NUMBER (9)
                        ,NOMBRE VARCHAR2 (9)
                        ,CONSTRAINT PK_COMPONENTE PRIMARY KEY (ID_COMPONENTE));
                        
CREATE TABLE TRANSPORTISTA (ID_TRANSPORTISTA NUMBER (9)
                            ,NOMBRE VARCHAR2 (25)
                            ,DIRECCION VARCHAR2 (25)
                            ,CONSTRAINT PK_TRANSPORTISTA PRIMARY KEY (ID_TRANSPORTISTA));
                            
CREATE TABLE CIUDAD (ID_CIUDAD NUMBER (9)
                    ,NOMBRE VARCHAR2 (25)
                    ,CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD));
                    
CREATE TABLE ENVASE (ID_ENVASE NUMBER (9)
                    ,TIPO VARCHAR2 (25)
                    ,CONSTRAINT PK_ENVASE PRIMARY KEY (ID_ENVASE));
                    
CREATE TABLE RESIDUO (ID_RESIDUO NUMBER (9)
                     ,ID_EMPRESA NUMBER (9)
                     ,NOMBRE VARCHAR2 (25)
                     ,CODIGO VARCHAR2 (25)
                     ,CONSTRAINT FK_EMPRESA_RESIDUOS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA (ID_EMPRESA)
                     ,CONSTRAINT PK_RESIDUO PRIMARY KEY (ID_RESIDUO)
                     ,CONSTRAINT UQ_CODIGO UNIQUE(CODIGO));
                     
CREATE TABLE COMPOSICION (ID_COMPOSICION NUMBER (9)
                         ,ID_RESIDUO NUMBER (9)
                         ,ID_COMPONENTE NUMBER (9)
                         ,PROPORCION VARCHAR2 (25)
                         ,CONSTRAINT PK_COMPOSICION PRIMARY KEY (ID_COMPOSICION)
                         ,CONSTRAINT FK_RESIDUO_COMPOSICION FOREIGN KEY (ID_RESIDUO) REFERENCES RESIDUO(ID_RESIDUO)
                         ,CONSTRAINT FK_COMPONENTE_COMPOSICION FOREIGN KEY (ID_COMPONENTE) REFERENCES COMPONENTE(ID_COMPONENTE));
                         
CREATE TABLE TRASLADO (ID_TRASLADO NUMBER (9)
                      ,ID_RESIDUO NUMBER (9)
                      ,ID_TRANSPORTISTA NUMBER (9)
                      ,ID_ENVASE NUMBER (9)
                      ,ID_CIUDAD NUMBER (9)
                      ,FECHA DATE 
                      ,COSTE NUMBER (6)
                      ,DURACION NUMBER (6)
                      ,CANTIDAD NUMBER (6)
                      ,CONSTRAINT PK_TRASLADO PRIMARY KEY (ID_TRASLADO)
                      ,CONSTRAINT FK_RESIDUO_TRASLADO FOREIGN KEY (ID_RESIDUO) REFERENCES RESIDUO(ID_RESIDUO)
                      ,CONSTRAINT FK_TRANSPORTISTA_TRASLADO FOREIGN KEY (ID_TRANSPORTISTA) REFERENCES TRANSPORTISTA (ID_TRANSPORTISTA)
                      ,CONSTRAINT FK_ENVASE_TRASLADO FOREIGN KEY (ID_ENVASE) REFERENCES ENVASE(ID_ENVASE)
                      ,CONSTRAINT FK_CIUDAD_TRASLADO FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD));
                      
                      



                                                      