--1--
DESC COUNTRIES;
DESC DEPARTMENTS;
DESC EMPLOYEES;
DESC JOB_HISTORY;
DESC JOBS;
DESC LOCATIONS;
DESC REGIONS;

--2--
SELECT JOB_ID, DEPARTMENT_ID
FROM JOB_HISTORY;

--3--
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

--4--
SELECT COUNT (COUNTRY_NAME)
FROM COUNTRIES
WHERE REGION_ID ='1';

--5--
SELECT 'THE EMPLOYEE ' ||FIRST_NAME|| LAST_NAME|| ' HAS A SALARY OF ' ||SALARY AS SENTENCE
FROM EMPLOYEES;

--6--
SELECT 'THE EMPLOYEE' || EMPLOYEE_ID || ' HAS BEEN WORKING IN THIS COMPANY SINCE ' || START_DATE || ' UNTIL ' || END_DATE || '. TOTAL YEARS: ' || (END_DATE-START_DATE)/365.25 AS SENTENCE
FROM JOB_HISTORY;

--7--
SELECT 22/7*(6000*6000)AS AREA
FROM DUAL;

--8--
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>5000;

--9--
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE SALARY != DEPARTMENT_ID;

--10--
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME <'KING';

--11--
 SELECT *
 FROM EMPLOYEES
 WHERE HIRE_DATE > '1/1/2000';
 
 --12--
 SELECT FIRST_NAME, HIRE_DATE
 FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN '24/07/1994' AND '07/06/1996';
