--1--
DESC COUNTRIES;
DESC DEPARTMENTS;
DESC EMPLOYEES;
DESC JOB_HISTORY;
DESC JOBS;
DESC LOCATIONS;
DESC REGIONS;

--2--
SELECT JOB_ID, DEPARTMENT_ID
FROM JOB_HISTORY;

--3--
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

--4--
SELECT COUNT (COUNTRY_NAME)
FROM COUNTRIES
WHERE REGION_ID ='1';

--5--
SELECT 'THE EMPLOYEE ' ||FIRST_NAME|| LAST_NAME|| ' HAS A SALARY OF ' ||SALARY AS SENTENCE
FROM EMPLOYEES;

--6--
SELECT 'THE EMPLOYEE' || EMPLOYEE_ID || ' HAS BEEN WORKING IN THIS COMPANY SINCE ' || START_DATE || ' UNTIL ' || END_DATE || '. TOTAL YEARS: ' || (END_DATE-START_DATE)/365.25 AS SENTENCE
FROM JOB_HISTORY;

--7--
SELECT 22/7*(6000*6000)AS AREA
FROM DUAL;

--8--
SELECT FIRST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY>5000;

--9--
SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
WHERE SALARY != DEPARTMENT_ID;

--10--
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME <'King';

--11--
 SELECT *
 FROM EMPLOYEES
 WHERE HIRE_DATE > '1/1/2000';
 
 --12--
 SELECT FIRST_NAME, HIRE_DATE
 FROM EMPLOYEES
 WHERE HIRE_DATE BETWEEN '24/07/1994' AND '07/06/1996';
 
 --13--
 SELECT LAST_NAME
 FROM EMPLOYEES
 WHERE LAST_NAME IN ('De Haan', 'Seo', 'Fripp');
 
 --14--
 SELECT COUNTRY_NAME
 FROM COUNTRIES
 WHERE COUNTRY_NAME like 'I%' OR  COUNTRY_NAME like '%a%';
 
  SELECT COUNTRY_NAME
 FROM COUNTRIES
 WHERE COUNTRY_NAME like '____a';
 
 --15--
 SELECT FIRST_NAME, LAST_NAME, COMMISSION_PCT, HIRE_DATE
 FROM EMPLOYEES
 WHERE FIRST_NAME != '%B' AND COMMISSION_PCT > 0.35;
 
 --16--
 SELECT LAST_NAME, SALARY, COMMISSION_PCT, DEPARTMENT_ID, JOB_ID
 FROM EMPLOYEES
 WHERE (LAST_NAME LIKE '%a%' AND SALARY > (DEPARTMENT_ID*200)) OR (JOB_ID IN ('MK_REP', 'MK_MAN') AND COMMISSION_PCT !=NULL);
 
 --17--
 SELECT JOB_TITLE, MIN_SALARY, MAX_SALARY, (MAX_SALARY-MIN_SALARY) AS VARIANCE
 FROM JOBS 
 WHERE JOB_TITLE IN ('%President%', '%Manager%')
 ORDER BY JOB_TITLE DESC;
 
 --18--
 SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, (SALARY*12) AS "SALARIO ANUAL", &&TAX_RATE, &TAX_RATE *(SALARY*12) AS TAX
 FROM EMPLOYEES
 WHERE EMPLOYEE_ID = &EMPLOYEE_ID;
 
 --19--
 SELECT FIRST_NAME, LAST_NAME
 FROM EMPLOYEES
 WHERE LOWER (LAST_NAME) LIKE '%ur%'; 
 
 --20--
SELECT FIRST_NAME, LAST_NAME
 FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '%li%';
 
 --21--
 SELECT  'NOMBRE ' || FIRST_NAME || ' APELLIDOS ' || LAST_NAME || ' GANA ' || SALARY || ' DE SALARIO '
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 100;
 
 --22--
 SELECT SUBSTR (FIRST_NAME, 1, 1) || '. ' || LAST_NAME
 FROM EMPLOYEES
 WHERE SUBSTR (JOB_ID, 1,2) LIKE 'AD';
 
 --23--
  SELECT SUBSTR (FIRST_NAME, 1, 1) || '. ' || REPLACE (LAST_NAME, ' ', '')
 FROM EMPLOYEES
 WHERE SUBSTR (JOB_ID, 1,2) LIKE 'AD';
 
 --24--
 SELECT FIRST_NAME, LAST_NAME, MOD(SALARY, 12) AS "SALARIO SIN PAGA EXTRA"
 FROM EMPLOYEES;
 
 --25--
 SELECT JOB_TITLE, TO_CHAR (MAX_SALARY, '$99,999.99') AS "MAXIMO SALARIO"
 FROM JOBS;
 
 --26--
 SELECT TO_CHAR (SYSDATE, '"HOY ES "DAY" "DD" DE "MONTH "DE "YYYY') FECHA
 FROM DUAL;
 
 --27--
 SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
 FROM EMPLOYEES
 WHERE HIRE_DATE> '12/01/2000';
 
 --28--
 SELECT TO_NUMBER (SUBSTR(PHONE_NUMBER, 5, 12), '999.9999')
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 30;
 
 --29--
 SELECT LAST_NAME AS "APELLIDOS CON F ", NVL2 (COMMISSION_PCT, 'GANA', 'NO GANA') AS "¿COMISIONES?" , COMMISSION_PCT AS "LO QUE GANA"
 FROM EMPLOYEES
 WHERE LAST_NAME LIKE 'F%';
 
 --42--
 SELECT SUM (SYSDATE-HIRE_DATE)
 FROM EMPLOYEES;
 
 --43--
 SELECT MIN (SALARY), MIN (HIRE_DATE), MAX (SALARY), MIN (HIRE_DATE)
 FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP';
 
 --45--
 SELECT END_DATE, COUNT (*)
 FROM JOB_HISTORY
 GROUP BY END_DATE;
 
select end_date, start_date, count(*)
from hr.job_history
group by end_date, start_date;

--47--
SELECT DEPARTMENT_ID, COUNT (*) 
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID ASC;

--48--
SELECT COUNT (*) END_DATE, JOB_ID
FROM JOB_HISTORY
GROUP BY END_DATE, JOB_ID
ORDER BY JOB_ID DESC;

--49--
SELECT TO_CHAR(HIRE_DATE, 'DAY')
FROM EMPLOYEES
GROUP BY TO_CHAR (HIRE_DATE, 'DAY')
HAVING COUNT (*)>15;

--50--
SELECT AVG (SALARY) AS "MEDIA DE SALARIO", COUNT(*) JOB_ID
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG (SALARY) >10000;

--NUEVOS EJERCICIOS--

--1--
SELECT FIRST_NAME, LAST_NAME, JOB_TITLE
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID;

--2--
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--3--
SELECT REGION_NAME, COUNTRY_NAME
FROM REGIONS R, COUNTRIES C
WHERE R.REGION_ID = C.REGION_ID
ORDER BY r.region_name;

--4--
SELECT REGION_NAME, COUNTRY_NAME
FROM REGIONS R, COUNTRIES C
WHERE R.REGION_ID = C.REGION_ID
ORDER BY REGION_NAME, COUNTRY_NAME;

--5--
SELECT  R.REGION_ID, R.REGION_NAME, C.COUNTRY_NAME
FROM COUNTRIES C, REGIONS R
WHERE R.REGION_ID = C.REGION_ID AND R.REGION_NAME = 'Asia';

--6--
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND HIRE_DATE BETWEEN '10/06/2005' AND '16/07/2006';

--7--
SELECT R.REGION_NAME, C.COUNTRY_NAME, L.STREET_ADDRESS, L.CITY
FROM COUNTRIES C, LOCATIONS L, REGIONS R
WHERE R.REGION_ID = C.REGION_ID AND C.COUNTRY_ID = L.COUNTRY_ID
ORDER BY REGION_NAME ASC, COUNTRY_NAME DESC;

--8--
































