--CREA UN PUNTO DE GUARDADO
SAVEPOINT SALVADO;

--INSERTA 3 REGISTROS EN LA TABLA REGIONS
INSERT INTO REGIONS (REGION_ID, REGION_NAME)
VALUES (5, 'ANTARTICA');

--MUESTRA LOS CAMBIOS REALIZADOS
SELECT REGION_ID, REGION_NAME
FROM REGIONS
WHERE region_id = 5 AND region_name = 'ANTARTICA';

--CREA UN SEGUNDO PUNTO DE GUARDADO
SAVEPOINT SALVADO2;

--MUESTRA LOS CAMBIOS

--CREA UNA VISTA QUE UNA DOS TABLAS

--VUELVE AL PRIMER PUNTO DE GUARDADO

--MUESTRA LOS CAMBIOS