--DROP TABLE REVISTA CASCADE CONSTRAINTS;
  --DROP TABLE AUTOR CASCADE CONSTRAINTS;
  --DROP TABLE SECCION CASCADE CONSTRAINTS;
  --DROP TABLE ARTICULO CASCADE CONSTRAINTS;
  --DROP TABLE CORREO CASCADE CONSTRAINTS;
  --DROP TABLE PUBLICACION CASCADE CONSTRAINTS;
  --DROP TABLE COMPOSICION CASCADE CONSTRAINTS;    
 
 
CREATE SEQUENCE SEQ_REVISTA;
CREATE SEQUENCE SEQ_AUTOR;
CREATE SEQUENCE SEQ_SECCION;
CREATE SEQUENCE SEQ_ARTICULO;
CREATE SEQUENCE SEQ_CORREO;
CREATE SEQUENCE SEQ_PUBLICACION;
CREATE SEQUENCE SEQ_COMPOSICION;

    CREATE TABLE REVISTA (ID_REVISTA NUMBER,
    		           NUMERO NUMBER,
    		           TIRADA NUMBER,
    		           FECHA DATE,
    		           CONSTRAINT PK_REVISTA PRIMARY KEY (ID_REVISTA),
                       CONSTRAINT UQ_REVISTA UNIQUE (NUMERO));
    
    CREATE TABLE AUTOR (ID_AUTOR NUMBER,
                        EMAIL VARCHAR2(30),
                        TEL NUMBER,
                        PSEUNO VARCHAR2 (20),
                        NOMBRE VARCHAR2(30),
                        EXTERNO VARCHAR2(1),
                        COLABO VARCHAR2(1),
                        CONSTRAINT PK_AUTOR PRIMARY KEY (ID_AUTOR),
                        CONSTRAINT UQ_AUTOR_EMAIL UNIQUE (EMAIL),
                        CONSTRAINT UQ_AUTOR_TEL UNIQUE (TEL),
                        CHECK (EXTERNO = 'S' OR EXTERNO = 'NO' AND COLABO = 'S' OR COLABO ='N'));
    
    CREATE TABLE SECCION (ID_SECCION NUMBER,
                         AMBITO VARCHAR2(10),
                         PRIO NUMBER,
                         ID_REVISTA NUMBER,
                         CONSTRAINT PK_SECCION PRIMARY KEY (ID_SECCION),
                         CONSTRAINT FK_REVISTA FOREIGN KEY (ID_REVISTA) REFERENCES REVISTA (ID_REVISTA));
    
    CREATE TABLE  ARTICULO (ID_ARTICULO NUMBER,
                           TITULO VARCHAR2(50),
                           SUBTITULO VARCHAR2(70),
                           CONTENIDO VARCHAR2(500),
                           PUBLICADO VARCHAR2(1),
                           ID_AUTOR NUMBER,
                           CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),
                           CONSTRAINT FK_ARTICULO FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID_AUTOR),
                           CHECK (PUBLICADO = 'S' OR PUBLICADO = 'NO'));
    
    CREATE TABLE  CORREO (ID_CORREO NUMBER,
                          ID_AUTOR NUMBER,
                          FECHA_ENTRA DATE,
                          ASUNTO VARCHAR2(10),
                          ADJUNTO BLOB,
                          ACCION VARCHAR2(1),
                          CONSTRAINT PK_CORREO PRIMARY KEY (ID_CORREO),
                          CONSTRAINT FK_CORREO FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID_AUTOR),
                          CHECK (ACCION = 'S' OR ACCION = 'O' OR ACCION = 'A' OR ACCION = 'E'));
    
    CREATE TABLE PUBLICACION (ID_PUBLICACION NUMBER,
                              ID_SECCION NUMBER,
                              ID_ARTICULO NUMBER,
                              PRIORI NUMBER,
                              CONSTRAINT PK_PUBLICACION PRIMARY KEY (ID_PUBLICACION),
                              CONSTRAINT FK_PUBLICACION_SECCION FOREIGN KEY (ID_SECCION) REFERENCES SECCION (ID_SECCION),
                              CONSTRAINT FK_PUBLICACION_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO));
    
    CREATE TABLE COMPOSICION(ID_COMPOSICION NUMBER,
    			     ID_CORREO NUMBER,
    			     ID_ARTICULO NUMBER,
    			     CONSTRAINT PK_COMPOSICION PRIMARY KEY (ID_COMPOSICION),
                     CONSTRAINT FK_COMPOSICION_CORREO FOREIGN KEY (ID_CORREO) REFERENCES CORREO (ID_CORREO),
                     CONSTRAINT FK_COMPOSICION_ARTICULO FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO));